#! /bin/sh
#
# sample configure call
#

CFLAGS="-g -Wall -Wshadow  -Wpointer-arith -Wcast-align -Winline -Wmissing-prototypes -Wmissing-declarations -Wnested-externs"
CXXFLAGS="-g -Wall -Wshadow  -Wpointer-arith -Wcast-align -Winline"

export CXXFLAGS CFLAGS

case `uname` in
	Linux)
		# defaults I use on Raspi OS
		./configure						\
			--with-html-dir=/var/www/html/meteo		\
			--with-browser-dir=/var/www/html/meteo/browser
		;;
	Darwin)
		# make sure mysql_config is on the PATH
		PATH=/usr/local/bin:/usr/local/mysql/bin:$PATH
		export PATH
		export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
		export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
		./configure						\
			--with-html-dir=/Library/WebServer/Documents/meteo \
			--with-browser-dir=/Library/WebServer/Documents/browser
		;;
	BSD/OS)
		# defaults proposed by Walter Poxon for BSD/OS 4.2
		limit datasize unlimited
		./configure						\
			--with-browser-dir=/usr/local/apache/cgi-bin
		;;
esac

